import Head from "next/head";
import { Col, Row } from "reactstrap";
import SalesChart from "../pannel/components/dashboard/SalesChart";
import Feeds from "../pannel/components/dashboard/Feeds";
import ProjectTables from "../pannel/components/dashboard/ProjectTable";
import TopCards from "../pannel/components/dashboard/TopCards";


export default function Home() {
  return (
    <>
      <Head>
        <title>ERP System</title>
        <meta name="description" content="Generated by erp system" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div>
        {/***Top Cards***/}
        <Row>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-success text-success"
              title="Profit"
              subtitle="Yearly Earning"
              earning="$21k"
              icon="bi bi-wallet"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-danger text-danger"
              title="Refunds"
              subtitle="Refund given"
              earning="$1k"
              icon="bi bi-coin"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-warning text-warning"
              title="New Project"
              subtitle="Yearly Project"
              earning="456"
              icon="bi bi-basket3"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-info text-into"
              title="Sales"
              subtitle="Weekly Sales"
              earning="210"
              icon="bi bi-bag"
            />
          </Col>
        </Row>
        {/***Sales & Feed***/}
        <Row>
          <Col sm="12" lg="12">
            <SalesChart />
          </Col>
        </Row>
        {/***Table ***/}
        <Row>
          <Col lg="6" xxl="8" sm="12">
            <ProjectTables />
          </Col>
          <Col sm="12" lg="6" xl="5" xxl="4">
            <Feeds />
          </Col>
        </Row>
      </div>
      </main>
    </>
  )
}
